/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.entities {

    [Bindable]
    [RemoteClass(alias="com.wineshop.entities.AbstractEntity")]
    public class AbstractEntity extends AbstractEntityBase {
    }
}