/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.entities {
	
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="com.wineshop.entities.Vineyard")]
    public class Vineyard extends VineyardBase {
		
		public function Vineyard():void {
			wines = new ArrayCollection();
		}
    }
}