/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.wineshop.entities {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.wineshop.entities.Wine$Type")]
    public class Wine$Type extends Enum {

        public static const RED:Wine$Type = new Wine$Type("RED", _);
        public static const WHITE:Wine$Type = new Wine$Type("WHITE", _);
        public static const ROSE:Wine$Type = new Wine$Type("ROSE", _);

        function Wine$Type(value:String = null, restrictor:* = null) {
            super((value || RED.name), restrictor);
        }

        protected override function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [RED, WHITE, ROSE];
        }

        public static function valueOf(name:String):Wine$Type {
            return Wine$Type(RED.constantOf(name));
        }
    }
}